version: '3'
services:
  postgresql:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=agregator
      - POSTGRES_USER=scraper
      - POSTGRES_PASSWORD=scraper123

  redis:
    image: "redis:alpine"

  agregator:
    build: .
    command: supervisord -n
    working_dir: /app
    ports:
      - "8000:8000"
      - "9001:9001"
    volumes:
      - .:/app

    environment:
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432

    links:
      - postgresql
      - redis

volumes:
  postgres_data: