# Generated by Django 2.2 on 2019-04-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteurl',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
